# Generated by Django 3.1.4 on 2021-01-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='shops',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
