# Generated by Django 3.1.4 on 2021-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20210101_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='verification_otp',
            field=models.CharField(default='', max_length=30),
        ),
    ]
