# Generated by Django 3.1.4 on 2021-01-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customers',
            name='payment_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
