# Generated by Django 3.1.4 on 2021-01-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210102_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
