# Generated by Django 3.1.4 on 2021-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210102_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='verification_otp',
            field=models.CharField(default='', max_length=30),
        ),
    ]
